server:
  port: 9191

#mybatis
mybatis:  
  typeAliasesPackage: com.example.demo.entity  
  mapperLocations: classpath:/com/example/demo/mapper/*.xml  
  configLocation: classpath:/mybatis-config.xml
  
# password Helpe_Imarket_123
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iMarket_Refactor
    username: root
    password: Helpe_Imarket_123
    driverClassName: com.mysql.jdbc.Driver  